// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJjyMte7kksVVQpGnuRlQgF5IEbqNdCw',
    appId: '1:465611512920:web:52ce576cb99761c0f0fe2d',
    messagingSenderId: '465611512920',
    projectId: 'you-can-education',
    authDomain: 'you-can-education.firebaseapp.com',
    storageBucket: 'you-can-education.firebasestorage.app',
    measurementId: 'G-1DGC9YMH1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2W1wyl8Cqi8L7IzfoKl7o9T5JWxYecY',
    appId: '1:465611512920:android:1f1e9c80483fbd5df0fe2d',
    messagingSenderId: '465611512920',
    projectId: 'you-can-education',
    storageBucket: 'you-can-education.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvDPdjC-BUL8k8RrYuO-QiQRmm3NZXL8',
    appId: '1:465611512920:ios:0a3495240322d77df0fe2d',
    messagingSenderId: '465611512920',
    projectId: 'you-can-education',
    storageBucket: 'you-can-education.firebasestorage.app',
    iosBundleId: 'com.example.gradProjectVer1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvDPdjC-BUL8k8RrYuO-QiQRmm3NZXL8',
    appId: '1:465611512920:ios:0a3495240322d77df0fe2d',
    messagingSenderId: '465611512920',
    projectId: 'you-can-education',
    storageBucket: 'you-can-education.firebasestorage.app',
    iosBundleId: 'com.example.gradProjectVer1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfJjyMte7kksVVQpGnuRlQgF5IEbqNdCw',
    appId: '1:465611512920:web:72b609e470a1b712f0fe2d',
    messagingSenderId: '465611512920',
    projectId: 'you-can-education',
    authDomain: 'you-can-education.firebaseapp.com',
    storageBucket: 'you-can-education.firebasestorage.app',
    measurementId: 'G-PH9T2QENP4',
  );
}
